# Generated by Django 3.1.4 on 2021-06-26 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_studentqueries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentqueries',
            old_name='data',
            new_name='date',
        ),
    ]
