# Generated by Django 3.1.4 on 2021-06-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210626_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentqueries',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studentqueries',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
